version: 0.1

phases:
    build:
        commands:
            - echo Nothing to do yet
            
artifacts:
    files:
        - index.html
        - error.html
        - babel.html
        - react.html
